pipeline:
  identifier: Build_go_fruits_api_1686138886411
  name: Build go-fruits-api
  orgIdentifier: default
  projectIdentifier: OWASP
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1683015583249
        repoName: yash-harnessio/go-fruits-api
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: BEE
                  identifier: BEE
                  spec:
                    shell: Python
                    command: |
                      import requests
                      import json

                      api_key = "j93nakD8xJgTJMjXu1xztavmgYe8bRRh"
                      scan_id = "1"
                      api_url = f"https://99d7-34-93-204-95.ngrok-free.app/api/{api_key}/v0.1/scan/{scan_id}"


                      response = requests.get(api_url)

                      data = response.json()
                      issue_events = data.get("issue_events", [])
                      issues = [event["issue"]["name"] for event in issue_events]

                      if issues != "":
                          print("Issues found:")
                          for issue in issues:
                              print(issue)
                          raise ValueError("Vulnerabilities found")
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
        when:
          pipelineStatus: All
