pipeline:
  identifier: Build_go_fruits_api_1686138886411
  name: Build go-fruits-api
  orgIdentifier: default
  projectIdentifier: OWASP
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1683015583249
        repoName: yash-harnessio/go-fruits-api
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotest
                  name: go_test
                  spec:
                    command: go test -v ./...
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: BEE
                  identifier: BEE
                  spec:
                    shell: Sh
                    command: |-
                      #curl -vgw "\n" -X POST 'https://99d7-34-93-204-95.ngrok-free.app/api/j93nakD8xJgTJMjXu1xztavmgYe8bRRh/v0.1/scan' -d '{"name":"CI","urls":["https://ginandjuice.shop"]}'

                      api_key="j93nakD8xJgTJMjXu1xztavmgYe8bRRh"
                      scan_id="1"
                      api_url="https://99d7-34-93-204-95.ngrok-free.app/api/${api_key}/v0.1/scan/${scan_id}"

                      # Make the cURL request and store the response in a variable
                      response=$(curl -sgw "\n" -X GET "${api_url}")

                      # Extract the name of issues from the response using regex
                      issues=$(echo "${response}" | grep -oE '"name":"[^"]+"' | cut -d':' -f2 | tr -d '"')

                      # Print the names of the issues
                      if [[ -n "${issues}" ]]; then
                        echo "Names found:"
                        echo "${issues}"
                        exit 1
                      fi
                  failureStrategies:
                    - onFailure:
                        errors:
                          - InputTimeoutError
                        action:
                          type: MarkAsFailure
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
